build:
  nodes:
    analysis:
      tests:
        stop_on_failure: true
        override:
          - php-scrutinizer-run
      environment:
        php:
          version: '7.3'
  dependencies:
    override:
      - composer update -o --prefer-source --no-interaction

filter:
  excluded_paths:
    - 'Tests/*'
    - 'vendor/*'

tools:
  php_analyzer: true
  external_code_coverage: true
  php_code_sniffer: true
