language: php
sudo: false
matrix:
  include:
    - php: 7.0
    - php: 7.1
  fast_finish: true
before_script:
  - mkdir -p build/logs
  - composer update --prefer-dist --prefer-lowest --prefer-stable
script:
  - vendor/bin/phpunit
after_success:
  - travis_retry php vendor/bin/coveralls
